proy_sales/core/urls.py
from django.urls import path
from core import views
 
app_name='core' # define un espacio de nombre para la aplicacion
urlpatterns = [
    #Urls de vistas

   path('product_list/', views.product_List,name='product_list'),
   path('listas/', views.listas,name='listas'),
   path('product_create/', views.product_create,name='product_create'),
   path('product_update/<int:id>/', views.product_update,name='product_update'),
   path('product_delete/<int:id>/', views.product_delete,name='product_delete'),
   #urls de marcas
   path('brand_list/', views.brand_List,name='brand_list'),
   path('brand_create/', views.brand_create,name='brand_create'),
    path('brand_update/<int:id>/', views.brand_update,name='brand_update'),
    path('brand_delete/<int:id>/', views.brand_delete,name='brand_delete'),
   #urls de proveedores
   path('supplier_list/', views.supplier_list,name='supplier_list'),
   path('supplier_create/', views.supplier_create, name='supplier_create'),
   path('supplier_update/<int:id>/', views.supplier_update, name='supplier_update'),
   path('supplier_delete/<int:id>/', views.supplier_delete, name='supplier_delete'),
   #urls de categorias
   path('category_list/', views.category_List,name='category_list'),
   path ('category_create/', views.category_create,name='category_create'),
   path('category_update/<int:id>/', views.category_update,name='category_update'),
   path('category_delete/<int:id>/', views.category_delete,name='category_delete'),
]

proy_sales/proy_sales/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include
from core import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('signup/',views.signup,name='signup'),
    path('logout/',views.singuot,name='logout'),
    path('singin/',views.singin,name='singin'),
    
    path('', include('core.urls',namespace='core')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

proy_sales/core/forms.py
from django import forms
from core.models import Product , Category , Supplier , Brand
class ProductForm(forms.ModelForm):
        
    class Meta:
        model=Product
        fields=['description','price','stock','expiration_date','brand','supplier','categories','line','image']

class CategoryForm(forms.ModelForm):
    class Meta:
        model=Category
        fields=['description']
        
class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = ['name', 'ruc', 'address', 'phone']
        
class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = ['description']

proy_sales/core/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from core.models import Product , Category, Supplier, Brand
from core.forms import ProductForm , CategoryForm , SupplierForm, BrandForm
from django.contrib.auth.models import User
from django.contrib.auth import login , logout, authenticate
from django.db import IntegrityError

def home(request):
   data = {
        "title1":"Bienvenidos a la App de Ventas",
        "title2":"Super Mercado Economico"
   }
   return render(request,'core/home.html',data)

def signup(request):
    if request.method == "GET":
        return render(request, "signup.html",{
            'form' : UserCreationForm()
        })
    else:
        if request.POST["password1"] == request.POST["password2"]:
            try:
                user = User.objects.create_user(request.POST["username"], password=request.POST["password1"])
                user.save()
                login(request,user)
                return redirect("home")
            except IntegrityError: 
                return render(request, "signup.html",{
                    'form':UserCreationForm,
                    'error':'El usuario ya existe'
                    })
        return render(request, "signup.html",{
            'form':UserCreationForm,
            'error':'Las contraseñas no coinciden'
        }) 
def singuot(request):
    logout(request)
    return redirect("home")
def singin(request):
    if request.method == "GET":
        return render(request, "singin.html",{
            'form' : AuthenticationForm()
        })
    else:
        user = authenticate(request,username=request.POST["username"],password=request.POST["password"])
    if user is None:
        return render(request, "singin.html",{
            'form':AuthenticationForm,
            'error':'El usuario o la contraseña no son correctos'
        })
    else:
        login(request,user)
        return redirect("home")

def listas(request):
    data = {
        "title1": "Productos del almaces",
        "title2": "Listas de Productos"
    }
    products=Product.objects.all()
    data["products"]=products
    return render(request,"core/products/listas.html",data)
#Vista de productos :listar,crear,editar,eliminar
def product_List(request):
    data = {
        "title1": "Productos",
        "title2": "Consulta De Productos"
    }
    products = Product.objects.all() # SELECT * FROM Product
    data["products"]=products
    return render(request,"core/products/list.html",data)
#Crear un producto
def product_create(request):
    data = {"title1": "Productos","title2": "Ingreso De Productos"}
   
    if request.method == "POST":
        print(request.POST)
        form = ProductForm(request.POST,request.FILES)
        
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.save()
            return redirect("core:product_list")

    else:
        data["form"] = ProductForm() # controles formulario sin datos

    return render(request, "core/products/form.html", data)
#Editar un producto
def product_update(request,id):
    data = {
        "title1": "Productos",
        "title2": "Editar Producto"
    }
    product=Product.objects.get(pk=id)
    if request.method== 'POST':
        form=ProductForm(request.POST,request.FILES,instance=product)
        if form.is_valid():
            form.save()
            return redirect("core:product_list")
    else:
        form=ProductForm(instance=product)
        data["form"]=form

    return render(request,"core/products/form.html",data)
#Eliminar un producto
def product_delete(request,id):
    data = {
        "title1": "Productos",
        "title2": "Eliminar Producto"
    }
    product=Product.objects.get(pk=id)
    if request.method== 'POST':
        product.delete()
        return redirect("core:product_list")
    return render(request,"core/products/delete.html",data)
#Vista de marcas :listar,crear,editar,eliminar
def brand_List(request):
    data = {
        "title1": "Marcas",
        "title2": "Consulta De Marcas De Productos"
    }
    brands = Brand.objects.all() # SELECT * FROM Brand
    data["brands"]=brands
    return render(request,"core/brands/list.html",data)
def brand_create(request):
    data = {"title1": "Marcas","title2": "Ingreso De Marcas De Productos"}
   
    if request.method == "POST":
        print(request.POST)
        form = BrandForm(request.POST)
        
        if form.is_valid():
            brand = form.save(commit=False)
            brand.user = request.user
            brand.save()
            return redirect("core:brand_list")

    else:
        data["form"] = BrandForm() # controles formulario sin datos

    return render(request, "core/brands/form.html", data)
def brand_update(request,id):
    data = {
        "title1": "Marcas",
        "title2": "Editar Marca"
    }
    brand=Brand.objects.get(pk=id)
    if request.method== 'POST':
        form=BrandForm(request.POST,instance=brand)
        if form.is_valid():
            form.save()
            return redirect("core:brand_list")
    else:
        form=BrandForm(instance=brand)
        data["form"]=form

    return render(request,"core/brands/form.html",data)
def brand_delete(request,id):
    data = {
        "title1": "Marcas",
        "title2": "Eliminar Marca"
    }
    brand=Brand.objects.get(pk=id)
    if request.method== 'POST':
        brand.delete()
        return redirect("core:brand_list")
    return render(request,"core/brands/delete.html",data)
#Vista de proveedores :listar,crear,editar,eliminar
def supplier_list(request):
    data = {
        "title1": "Proveedores",
        "title2": "Consulta De Proveedores",
    }
    suppliers = Supplier.objects.all()
    data["suppliers"] = suppliers
    return render(request, 'core/suppliers/list.html', data)
#Crear un Proovedor
def supplier_create(request):
    data = {"title1": "Proveedores", "title2": "Ingreso De Proveedores"}
   
    if request.method == 'POST':
        form = SupplierForm(request.POST)
        if form.is_valid():
            supplier = form.save(commit=False)
            supplier.user = request.user
            supplier.save()
            return redirect('core:supplier_list')
    else:
        form = SupplierForm()
    data["form"] = form
    return render(request, 'core/suppliers/form.html', data)
#Modificar un Proovedor
def supplier_update(request, id):
    data = {"title1": "Proveedores", "title2": "Editar Proveedor"}
    supplier = Supplier.objects.get(pk=id)
    if request.method == 'POST':
        form = SupplierForm(request.POST, instance=supplier)
        if form.is_valid():
            form.save()
            return redirect('core:supplier_list')
    else:
        form = SupplierForm(instance=supplier)
    data["form"] = form
    return render(request, 'core/suppliers/form.html', data)
#Eliminar un Proovedor
def supplier_delete(request, id):
    data = {
        "title1": "Proovedores",
        "title2": "Eliminar Proovedor"
    }
    supplier = Supplier.objects.get(pk=id)
    if request.method == 'POST':
        supplier.delete()
        return redirect('core:supplier_list')
    return render(request, 'core/suppliers/delete.html', data)
#
def category_List(request):
    data = {
        "title1": "Categorias",
        "title2": "Consulta De Categorias"
    }
    categories = Category.objects.all() # SELECT * FROM Category
    data["categories"]=categories
    return render(request,"core/category/list.html",data)
def category_create(request):
    data = {"title1": "Categorias","title2": "Ingreso De Categorias"}
   
    if request.method == "POST":
        print(request.POST)
        form = CategoryForm(request.POST)
        
        if form.is_valid():
            category = form.save(commit=False)
            category.user = request.user
            category.save()
            return redirect("core:category_list")

    else:
        data["form"] = CategoryForm() # controles formulario sin datos

    return render(request, "core/category/form.html", data)

def category_update(request,id):
    data = {
        "title1": "Categorias",
        "title2": "Editar Categoria"
    }
    category=Category.objects.get(pk=id)
    if request.method== 'POST':
        form=CategoryForm(request.POST,instance=category)
        if form.is_valid():
            form.save()
            return redirect("core:category_list")
    else:
        form=CategoryForm(instance=category)
        data["form"]=form

    return render(request,"core/category/form.html",data)

def category_delete(request,id):
    data = {
        "title1": "Categorias",
        "title2": "Eliminar Categoria"
    }
    category=Category.objects.get(pk=id)
    if request.method== 'POST':
        category.delete()
        return redirect("core:category_list")
    return render(request,"core/category/delete.html",data)

proy_sales/templates/core/suppliers/delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="form-container">
    <form class="form-container" method="POST">
     {% csrf_token %}
     <h1 class="title">{{ title2 }}</h1>
     <h2>¿Desea Eliminar el Proveedor?
        <span>{{ supplier.id }} - {{ supplier.name }}</span>
     </h2>
     <div>
         <button class="btn blue" type="submit">Eliminar</button>
         <a class="btn red" href="{% url 'core:supplier_list' %}" >Regresar</a>
     </div>
    </form>
  </div>
</div>
{% endblock content %}

proy_sales/templates/core/suppliers/form.html
{% extends 'base.html' %}
{% block content %}
 <div class="container">
  <div class="form-container">
    <h2 class="title">{{title2}}</h2>
   
    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label for="{{field.id_for_label}}">{{field.label}}</label>
            {{field}}
            {% if field.errors %}
                <div class="form-errors">
                    <ul>
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>
        {% endfor %}
        <div class="form-group">
            <input type="submit" value="Guardar" class="btn blue">
            <a href={% url 'core:supplier_list' %} class="btn red"> Cancelar </a>
        </div>
    </form>
</div>
</div>
{% endblock content  %}

proy_sales/templates/core/suppliers/list.html
{% extends 'base.html' %}
{% block content %}
   <div class="table-container">
    <br>
    <h1 class="title">{{ title2 }}</h1>
    <table class="styled-table">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>RUC</th>
          <th>Dirección</th>
          <th>Teléfono</th>
          <th>Fecha de Creación</th>
          <th>Fecha de Modificación</th>
          <th>Estado</th>
          <th>Acciones</th>
      </tr>
      </thead>
      <tbody>
        {% for item in suppliers %}
          <tr>
          <td>{{item.name}}</td>
          <td>{{item.ruc}}</td>
          <td>{{item.address}}</td>
          <td>{{item.phone}}</td>
          <td>{{item.created|date:"Y-m-d"}}</td>
          <td>{{item.updated|date:"Y-m-d"}}</td>
          <td>{% if item.state %}
               ✔
              {% else %}
               ➖
              {% endif %}
          </td>
          <td>
            <a href={% url 'core:supplier_update' item.id  %}>✏️</a>
            <a href={% url 'core:supplier_delete' item.id  %}>❌</a>
          </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
     <div class="form-group">
       <a class="btn blue" href={% url 'core:supplier_create' %}>Nuevo Proveedor</a>
     </div>
  </div>
{% endblock content  %}