proy_sales/core/urls.py
from django.urls import path
from core import views
 
app_name='core' # define un espacio de nombre para la aplicacion
urlpatterns = [
    #Urls de vistas

   path('product_list/', views.product_List,name='product_list'),
   path('listas/', views.listas,name='listas'),
   path('product_create/', views.product_create,name='product_create'),
   path('product_update/<int:id>/', views.product_update,name='product_update'),
   path('product_delete/<int:id>/', views.product_delete,name='product_delete'),
   #urls de marcas
   path('brand_list/', views.brand_List,name='brand_list'),
   path('brand_create/', views.brand_create,name='brand_create'),
    path('brand_update/<int:id>/', views.brand_update,name='brand_update'),
    path('brand_delete/<int:id>/', views.brand_delete,name='brand_delete'),
   #urls de proveedores
   path('supplier_list/', views.supplier_list,name='supplier_list'),
   path('supplier_create/', views.supplier_create, name='supplier_create'),
   path('supplier_update/<int:id>/', views.supplier_update, name='supplier_update'),
   path('supplier_delete/<int:id>/', views.supplier_delete, name='supplier_delete'),
   #urls de categorias
   path('category_list/', views.category_List,name='category_list'),
   path ('category_create/', views.category_create,name='category_create'),
   path('category_update/<int:id>/', views.category_update,name='category_update'),
   path('category_delete/<int:id>/', views.category_delete,name='category_delete'),
]

proy_sales/proy_sales/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include
from core import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('signup/',views.signup,name='signup'),
    path('logout/',views.singuot,name='logout'),
    path('singin/',views.singin,name='singin'),
    
    path('', include('core.urls',namespace='core')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

proy_sales/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <title>{% block title %}{{ title1 }}{% endblock %}</title>
</head>
<body>
  <header id="header">
    <span class="logo">SMART ZONE</span>
    <nav>
      <ul class="menu">
        <li><a href="{% url 'home' %}">Inicio</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'core:product_list' %}">Productos</a></li>
        <li><a href="{% url 'core:brand_list' %}">Marcas</a></li>
        <li><a href="{% url 'core:category_list' %}">Categorias</a></li>
        <li><a href="{% url 'core:supplier_list' %}">Proveedores</a></li>
        <li><a href="{% url 'logout' %}">Desconectarse</a></li>
        {% else %}
        <li><a href="{% url 'singin' %}">Iniciar Sesión</a></li>
        <li><a href="{% url 'signup' %}">Registrarse</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <main id="content">
    {% block content %}
    {% endblock content %}
  </main>
</body>
</html>

proy_sales/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Registrarse{% endblock %}

{% block content %}
<div class="login-container">
<h1>Registrarse</h1>

<form action="/signup/" method="POST">
    {{error}}
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Registrarse</button>
</form>
{% endblock%}

proy_sales/templates/singin.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Inicio de sesión{% endblock %}

{% block extra_styles %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock extra_styles %}

{% block content %}
<div class="login-container">
    <h1>Iniciar sesión</h1>
    
    <form action="/singin/" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Iniciar</button>
    </form>
  </div>
</div>
{% endblock %}